=== Manishfoodtechs/OEM/php/App/model.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/model.dtd

    <!DOCTYPE model SYSTEM "model.dtd">
-->

<!ELEMENT model (table|template|import)*>
<!ATTLIST model
    collate CDATA #IMPLIED
    charset CDATA #IMPLIED
    engine CDATA #IMPLIED
  >

<!ELEMENT import EMPTY>
<!ATTLIST import
	name CDATA #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT template (index*,unique*,field*)>
<!ATTLIST template
    name CDATA #REQUIRED
    primary_key CDATA #IMPLIED
    index CDATA #IMPLIED
    unique CDATA #IMPLIED
    default CDATA #IMPLIED
    size CDATA #IMPLIED
    null CDATA #IMPLIED
    type CDATA #IMPLIED
    auto_increment CDATA #IMPLIED
    signed CDATA #IMPLIED
    extends CDATA #IMPLIED
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT table (index*,unique*,field*)>
<!ATTLIST table
    name CDATA #REQUIRED
    primary_key CDATA #IMPLIED
    null CDATA #IMPLIED
    collate CDATA #IMPLIED
    charset CDATA #IMPLIED
    engine CDATA #IMPLIED
    extends CDATA #IMPLIED
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #IMPLIED
    index CDATA #IMPLIED
    unique CDATA #IMPLIED
    default CDATA #IMPLIED
    size CDATA #IMPLIED
    null CDATA #IMPLIED
    type CDATA #IMPLIED
    auto_increment CDATA #IMPLIED
    extends CDATA #IMPLIED
  >

<!ELEMENT index (#PCDATA)>

<!ELEMENT unique (#PCDATA)>

=== Manishfoodtechs/OEM/php/App/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "model.dtd">
<model engine="InnoDB" charset="utf8" collate="utf8_general_ci">

	<import name="model-templates"/>
	
	<table name="item" primary_key="id">
		<!-- technical -->
		<field name="id"                extends="item_id" auto_increment="y"/>
		<field extends="created"/>
		<field extends="updated"/>
		<field extends="author_id"/>
		<!-- general -->
		<field name="name"              extends="text"/>
		<field name="description"       extends="long_text"/>
	</table>

</model>

=== Manishfoodtechs/OEM/php/App/model-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "model.dtd">
<model engine="InnoDB" charset="utf8" collate="utf8_general_ci">

	<template name="id" type="int" size="5" signed="n" null="n" class="Int"/>
		<template name="item_id" extends="id"/>
		<template name="company_id" extends="id"/>
		<template name="collection_id" extends="id"/>
		<template name="filter_id" extends="id"/>
		<template name="author_id" extends="id"/>
	
	<template name="date" type="int" size="4" signed="n" null="n" class="Date"/>
		<template name="created" extends="date"/>
		<template name="updated" extends="date"/>

	<template name="choice" type="enum" class="Choice" null="n"/>
		<!--template name="user_status" extends="choice" size="new,confirmed,suspended" default="new"/>
		<template name="publish_status" extends="choice" size="live,edit,prev" default="live"/>
		<template name="moderation_status" extends="choice" size="new,accepted,removed" default="new"/-->

	<template name="long_text" type="text" null="n" class="Text"/>
	<template name="text" type="varchar" size="250" null="n" class="Text"/>
		<template name="short_text" extends="text" size="100"/>
		<template name="email" extends="text" class="Email"/>

	<template name="ip" type="int" size="4" signed="y" null="n" class="IP"/>

	<template name="data" type="blob" null="n"/>
	<template name="amount" type="decimal" size="5,2" null="n"/>
	<template name="hash" type="char" size="32" null="n"/>
		<template name="password" extends="hash"/>
		<template name="secret" extends="hash" size="16"/>

	<template name="byte" type="int" size="1" default="0" signed="n" null="n"/>
		<template name="switch" extends="byte"/>
		<template name="price" extends="byte" size="3"/>

</model>
